server:
  port: 9000


spring:
  cloud:
    gateway:
      routes:
        - id: add_header_filter
          uri: http://localhost:8080
          predicates:
            - Path=/info/header
          filters:
            - AddRequestHeader=X-Request-Color, blue
        - id: add_headers_if_not_present_filter
          uri: http://localhost:8080
          predicates:
            - Path=/info/allHeader
          filters:
            - AddRequestHeadersIfNotPresent=X-Request-Color:blue,City:beijing
        - id: custom_predicate
          uri: https://www.douban.com/
          predicates:
            - Auth=zhangsan, 12345
        - id: token_predicate
          uri: https://www.baidu.com
          predicates:
            - Token=12345


#        - id: my_route
#          uri: https://baidu.com
#          predicates:
#            - Path=/bd
#
#        - id: tb_route
#          uri: https://taobao.com
#          predicates:
#            - Path=/tb
#
#        - id: jd_route
#          uri: https://jd.com
#          predicates:
#            - Path=/jd

#        - id: after_router
#          uri: https://www.bilibili.com/
#          predicates:
#            - After=2025-10-01T10:10:10.789-07:00
#
#        - id: before_router
#          uri: https://www.youku.com
#          predicates:
#            - After=2025-10-01T10:10:10.789-07:00
#
#        - id: between_router
#          uri: https://www.iqiyi.com
#          predicates:
#            - Between=2025-10-01T10:10:10.789-07:00,2025-10-10T10:10:10.789-07:00
