server:
  port: 9000


spring:
  cloud:
    gateway:
      routes:
        - id: my_route
          uri: https://baidu.com
          predicates:
            - Path=/bd

        - id: tb_route
          uri: https://taobao.com
          predicates:
            - Path=/tb

        - id: jd_route
          uri: https://jd.com
          predicates:
            - Path=/jd
