server:
  port: 8081

spring:
  jpa:
    # auto create table
    generate-ddl: true
    #print sql
    show-sql: true
    # restart not update table
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&&userSSL=false&characterEncoding=utf8
    username: root
    password: password

logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: INFO
    org.hibernate: INFO
    # self code
    com.abc: DEBUG
#    # showsql = true
#    org.hibernate.type.descriptor.sql.BasicBinder: true
#    # showsql = true
#    org.hibernate.type.descriptor.sql.BasicExtractor: true